### DISCUSSION TITLE
Add global state for all tasks/targets

### DISCUSSION THREAD

**Discussion by korney4eg** [umputun/spot#103] [Ideas]
Based on ansible, terraform experience I came up with idea of having global state that could consist of some usefull information from all of tasks/targets.

Example state from [simplified  playbook](https://simplotask.com/?ref=producthunt#simplified-playbook-example) could look like map that I will show in yaml format:
```yaml
tasks_state:
  - name: wait
    target: target1
    status: success # this could be some predefined set of statuses, e.g. "success", "failed", "skipped"
    return_values:
      exit_code: 0
      std_out: ''
      std_err: ''
      execution_time: 
      ....
  - name: wait
    target: target2
    status: failed
    return_values:
      exit_code: 1
      std_out: ''
      std_err: 'no disc space left'
      execution_time: 5s
      ....
  - name: copy configuration
     target: target1
    status: success
     return_values:
       changed: false
       sha256: '73267ba...'
```

So later we can somehow reuse those values like we do it in ansible, but right now we can just print them out.

If you like this idea or you have your own idea of implementation I would like to participate.
