### DISCUSSION TITLE
export var=$(...)

### DISCUSSION THREAD

**Discussion by knutov** [umputun/spot#116] [Q&A]
```yaml
tasks:
  - name: uptime
    commands:
      - name: uptime_get
        script: |
          export random_var=$(/usr/bin/uptime)
      - name: uptime_debug
        echo: $random_var
```

`spot -t s2 --task uptime -v`

```
spot v1.6.3-004d58f-2023-05-29T05:28:37Z
[s2 some.server:22] run task "uptime", commands: 2
[s2 some.server:22]  > sh -c /tmp/.spot/spot-script1294900175
[s2 some.server:22]  ! /tmp/.spot/spot-script1294900175: 3: export: 02:16:43: bad variable name
[s2 some.server:22]  ! failed command "uptime_get" on host some.server:22 (s2): can't run script on some.server:22: failed to run command on remote server: Process exited with status 2
```

code looks correct. What "bad variable name" means in this case? Does everything parsed correctly?
