### DISCUSSION TITLE
Setting the environment variables from a file

### DISCUSSION THREAD

**Discussion by GhisF** [umputun/spot#126] [Ideas]
## Problem

The possibility to set variables only from the command line or from the playbook is not very flexible,
especially if we want to use a large number of variables or different sets of many variables.

## Propositions

The possibility to load variables from a file with an optionnal arg, for example ```-E```.
The file containing variables or sets of variables as a structured list of key:value pairs.

### The basic case, with a set of variables per files

```-E set1.yaml```

```yaml
- VAR1: A
- VAR2: B
```

### More sophisticated, with several sets of variables in a single file.

```-E severalSets.yaml:set_1```

```yaml
set_1:
  - VAR1: A
  - VAR2: B
set_2:
  - VAR1: C
  - VAR2: D
```

### Even better, the possibility to run the playbook on each set of variables of a file, eventually filtered by a regexp.
```-E severalSet.yaml:set_*```

Thanks

**Comment by umputun** [comment]
moved to discussions

**Reply by umputun** [reply]
I have added basic support for env file, see https://github.com/umputun/spot/pull/127 for more details.

**Reply by GhisF** [reply]
That works perfectly, thank you for your excellent work :).

If you plan to develop this feature, this is an exmple of what I have in mind.

Using this vars.toml
```
[[USER]]
name="name1"
UID="uid1"
GID="gid1"
HOMEDIR="homedir1"
[[USER]]
name="name2"
UID="uid2"
GID="gid2"
HOMEDIR="homedir2"
```

or vars.yml
```
USER:
  - name: name1
    UID: uid1
    GID: gid1
    HOMEDIR: homedir1
  - name: name2
    UID: uid2
    GID: gid2
    HOMEDIR: homedir2

  
```

A basic axemple of a commant using such structure in Spot.yml

```
  - name: AddUsers
    targets: ["dev"]
    commands:
      - name: addusers
        script: adduser -u $USER.UID -g $USER.GID -d $USER.HOMEDIR  $USER.NAME
```
