### DISCUSSION TITLE
Proposal: ability to specify default sh runner

### DISCUSSION THREAD

**Discussion by knutov** [umputun/spot#135] [Ideas]
Few weeks after #116  I came to those facts:

- some servers have `sh` to `dash` by default, some servers to `bash`
- dash and bash have incompatibilities, may be even in strict sh syntax
- dash is faster (some times x1.5..x2) but some code requires bash
- it is possible to specify interpreter in the shebang line
- but it takes one more line each task
- not possible to specify for short one-line commands
- behavior/result of task is unpredictable if interpreter is not set
- it is not possible to change sh to dash/bash on servers because of other software having some strict expectations

So, please, is it possible to add option "default interpreter"? With `/bin/sh` by default and possibility to set it to `/bin/bash` (or any other sh-compatible binary)

**Comment by umputun** [comment]
I have implemented it in PR #141 

Pls give it a try and see if this is what you want. This change introduced a new `--shell` (`$SPOT_SHELL`) parameter allowing to set a default shell runner for remote operations.

_if you don't know how to build this version, let me know what platform you need it, and I'll make a binary for you_

**Reply by knutov** [reply]
Thanks! 

I do `make` in wsl2 with latest go binary, It ends with error "Cannot connect to the Docker daemon at unix:///var/run/docker.sock." (and I do not have docker installed) but `make build` seems to be ok.

```
  - name: shell
    commands:
      - name: shell
        script: export S=$BASH_VERSION
      - name: shell_echo
        echo: $S
```

```bash
/home/kola/spot/.bin/spot.custom_shell --task=shell  -p test.yml -t s2 --shell=/bin/bash

...
failed, can't run task "shell" for target "s2": 1 error(s) occurred:
   [0] failed command "shell_echo" on host s2.hidden.net:22 (s2): can't run echo command on s2.hidden.net:22: failed to run command on remote server: Process exited with status 1

/home/kola/spot/.bin/spot.custom_shell --task=shell  -p test.yml -t s2 --shell=/bin/dash

...
completed command "shell_echo" {echo: } (53ms)
```

`/bin/bash` exists on remote server:

```
root@s2:~# ls -la /bin/bash
-rwxr-xr-x 1 root root 1183448 Apr 18  2022 /bin/bash*
```

Also, having possibility to set `shell: /bin/...` as part of yaml playbook (at global/task level) would be very convenient, I think

**Reply by umputun** [reply]
This issue doesn't have anything to do with the change. My guess is that the $BASH_VERSION env vars is not set for the ssh session. Try to change this script to something like this:

```
  - name: shell
    commands:
      - name: shell
        script: export S=$(date +%Y%m%d)
      - name: shell_echo
        echo: $S
```        

I have tested it with and without `--shell` params, and it worked fine

**Reply by umputun** [reply]
> Also, having possibility to set shell: /bin/... as part of yaml playbook (at global/task level) would be very convenient, I think

It makes sense, added https://github.com/umputun/spot/pull/141/commits/6ebd598e85afe7489571fb1db7a0561d76f4b411

**Reply by knutov** [reply]
> This issue doesn't have anything to do with the change.

I was expecting to use $BASH_VERSION as test that script was executed via bash.

with `--dry` I see

```text
! command script /tmp/.spot-6550957430088598528/spot-script2800623316
#!/bin/bash
set -e
export S=$BASH_VERSION
echo setvar S=${S}
```

I saved this to file, did chmod 700 and:

```bash
 ./test.bash
setvar S=5.0.17(1)-release
```

When I do ` ssh s2 /root/test.bash` I've got the same `setvar S=5.0.17(1)-release`, so it seems this should work also with spot.

**Reply by knutov** [reply]
The interesting thing - it works with backslash:

```
        script: export S=\$BASH_VERSION
```

Did spot substitute variables before sending them to remote server or what else could it be?

**Reply by umputun** [reply]
from quick googling, it looks like $BASH_VERSION s a special shell variable in bash, not an environment variable. Maybe it has something to do with that, not sure.

**Reply by knutov** [reply]
well, It could be.

I checked with some bashism that works only with bash and all seems to be fine with some constructions like `for`. But I find another not working cases (may be not related to the shell feature):

```
script: function f { export S=passed; } ; f
```

![изображение](https://github.com/umputun/spot/assets/255869/74b0e3bb-d14d-410c-8c83-ce38b6683460)

![изображение](https://github.com/umputun/spot/assets/255869/ab0f7b17-a4dd-4d71-9f5f-f58049294c92)


There is no `setvar` in generated code and adding `export S=$S` at the end is not working here.


Also, there is some issue with generating code for dash version:

```
  - name: bash
    commands:
      - name: shell
        script: |
          f() { export S=passed; }
          f
      - name: shell_echo
        echo: $S
```

with `spot.custom_shell --task=bash  -p test.yml -t s2 --shell=/bin/bash --dry` it becomes:

![изображение](https://github.com/umputun/spot/assets/255869/1c33f6b9-fd1e-417d-b5d1-c4fcf5389af5)

Note calling function `f` is missing at the end of the script.

**Reply by umputun** [reply]
> Did spot substitute variables before sending them to remote server or what else could it be?

No, this temp script just uploaded and executed with `{shell} -c tempfile`. I even disabled the cleanup to check the content of this script on the remote server, and all I see here is the same script:

```
#!/bin/bash
set -e
export S=$BASH_VERSION
echo setvar S=${S}
```

I just tried to run it on a remote alpine server with bash installed, and it worked. 

```
 > go run cmd/spot/main.go -p spot-private.yml --target=dev1 --task=shell -v --shell=/bin/bash --dbg

sspot latest
[dev1 dev1.umputun.dev:22] run task "shell", commands: 2
[dev1 dev1.umputun.dev:22]  > /bin/bash -c /tmp/.spot-3138683680024295424/spot-script141964945
[dev1 dev1.umputun.dev:22]  > setvar S=5.2.15(1)-release
[dev1 dev1.umputun.dev:22] completed command "shell" {script: /bin/bash -c /tmp/.spot-3138683680024295424/spot-script141964945} (101ms)
[dev1 dev1.umputun.dev:22] script: /tmp/.spot-3138683680024295424/spot-script141964945
[dev1 dev1.umputun.dev:22]  + #!/bin/bash
[dev1 dev1.umputun.dev:22]  + set -e
[dev1 dev1.umputun.dev:22]  + export S=$BASH_VERSION
[dev1 dev1.umputun.dev:22]  + echo setvar S=${S}
[dev1 dev1.umputun.dev:22] completed command "shell_echo" {echo: 5.2.15(1)-release} (8ms)
[dev1 dev1.umputun.dev:22] completed task "shell", commands: 2 (186ms)
```

Well, initially, it failed on echo due to the missing quotes, i.e. `/bin/bash -c echo something` doesn't work on bash/alpine, but `/bin/bash -c "echo something"` does

**Reply by knutov** [reply]
with PR #145 it looks good, but there is still the case with 

```yaml
  - name: bash
    commands:
      - name: shell
        script: |-
          f() { export S=passed ; }
          f
      - name: shell_echo
        echo: "$S"
```

It does not work with `--shell=` bash or dash, but this version works:

```yaml
  - name: bash_test
    commands:
      - name: shell
        script: |-
          export S=not_ok # <-- this line added
          f() { export S=passed ; }
          f
      - name: shell_echo
        echo: "$S"
``` 

Not sure but it seems to be a bug with something about exporting variable to `spot`.

**Reply by umputun** [reply]
[Export capturing](https://github.com/umputun/spot/blob/9aab79956135d0595ef4acb01908494357d3c140/pkg/config/command.go#L204-L204) from the function won't work in this case, because it detects exported vars just by prefix. As you can see, the parsing here is very basic and expects `export foo=bar`. This doesn't feel like a bug to me but rather an expected limitation of the current implementation. 

_If you have bright ideas on how to extend it and what other use cases, pls share. This can probably be made smarter with regex, but I am not sure how safe this is going to be. Personally, I'm not even sure if support for such tricky cases is even needed in real life, as I don't think people are really going to use bash functions in playbooks._

**Reply by knutov** [reply]
This should be documented at least, I think.

I'll think is it possible to make it better without writing complex code.

**Reply by knutov** [reply]
As a WIP: I thought about `set -o posix ; set`, `env`, `export -p` and came to the idea that this is all weak and unpredictable. And having "export =" at only beginning of line is leading do missing all single line cases, spaces/tabs at the line start, complex cases where set/declare is used, etc.

As an other way it is possible to have

```yaml
script: |
  ...
register: var1
# or
register: [ "var2", "var3", ...]
```

This "register" supposed to add "setvar" strings to the end of script. And this seems to be reliable and predictable.

@umputun What do you think about it?
