### DISCUSSION TITLE
Support to copy file from remote target to local

### DISCUSSION THREAD

**Discussion by koolay** [umputun/spot#195] [Q&A] [answered]
Is there any way to copy file from remote target host to local?

**Comment by umputun** [comment]
for questions and similar types of clarification, please use https://github.com/umputun/spot/discussions/categories/q-a


moved

**Comment by umputun** [comment]
the short answer is no. Technically, the `copy` command can be extended to support the reversed direction, and this shouldn't be a big change. However, I don't really see a valid use case for this. If you have practical cases that warrant such an extension, please share.

**Reply by koolay** [reply]
A server command outputs a string as a variable in another server command.
First copy the content from server A to the local server, and then copy it to another remote server.

**Reply by umputun** [reply]
I understand what it's technically doing, but I still struggle to see why - i.e., what problem it's trying to solve. Can you give me more details on why this deployment process needs to run something on the first server, capture the output, copy it back to local, and then copy it to another server? What is this sequence supposed to achieve?

I'm asking all of this because my goal is to keep Spot simple and minimal, avoiding the creation of another complex beast with many functions that cater to extremely rare use cases.

**Reply by koolay** [reply]
In this case, the `register` not work.
```yaml
ssh_key: ~/.ssh/id_rsa
user: root
targets:
  master:
    hosts:
      - host: 192.168.1.10
        user: root
        port: 22
  worker:
    hosts:
      - host: 192.168.1.11
        user: root
        port: 22
tasks:
  - name: start master
    targets: [master]
    commands:
      - name: start server
        options: { sudo: true }
        script: |-
          master_token=$(cat ./start.sh | bash --start)
        register: [master_token]
  - name: start worker
    targets: [worker]
    commands:
      - name: start worker server
        options: { sudo: true }
         script: |-
           bash ./start.sh --join $master_token

```
