### DISCUSSION TITLE
Using 'nvm use'

### DISCUSSION THREAD

**Discussion by polderudo** [umputun/spot#226] [Q&A]
I have a smal script that should use 'nvm use' to set the npm version before building some frontend.

I use 
local_shell: /bin/bash

and also use a shebag
  ```
- name: build vue
    options: {local: true}
    commands:
      - name: del dist folder
        script: rm -rf $FRONTEND_LOCAL_DIR/dist
      - name: build vue
        script: |
          #!/bin/bash
          cd $FRONTEND_LOCAL_DIR
          nvm use
          npm run $NODE_BUILD_TARGET
```

but the task runs into error:
[localhost]  > /bin/sh -c /tmp/.spot-5237875189867584512/spot-script3544141793
[localhost]  ! /tmp/.spot-5237875189867584512/spot-script3544141793: line 10: nvm: command not found

nvm is not availabe in sh, only bash and zsh.
Any idea why the script does not use bash from the shebag but sh?
