### DISCUSSION TITLE
What are the reasoning for running all tasks in the playbook

### DISCUSSION THREAD

**Discussion by bessarabov** [umputun/spot#23] [General]
I'm thinking of using `spot` in my infrastructure, but I'm not sure that I feel the best practices of using it.

I was thinking to create a playbook like this:

```
user: my-user
ssh_key: ~/.ssh/id_rsa

targets:
  prod:
    hosts: [{host: "prod1.example.com"}, {host: "prod2.example.com"}]
  dev:
    hosts: [{ host: "dev.example.com" }]

tasks:
  deploy-api:
    commands:
      - script: docker pull ...
      - script: docker rm -f ...
      - script: docker run ...

  deploy-front:
    commands:
      - script: docker pull ...
      - script: docker rm -f ...
      - script: docker run ...

  enable-api-debug:
    commands:
      - script: touch .../debug

  disalbe-api-debug:
    commands:
      - delete: {"path": ".../debug" }

  run-maintenance-1:
    commands:
      - script: ...
```

So it contains some tasks that I would like to execute on the remote hosts.

But I'm surprised with the logic that by default all the tasks are executed:

> Run SimploTask using the following command: spot. This will execute all the tasks defined in the default spot.yml file for the default target with a concurrency of 1.

Probably this is a good thing, but this does not play well with the workflow I was planning to implement — I'm expecting to have difrent tasks that I never need to run all at once (but it is quite possible that what I want to do is not the main idea of this software and it should not be supported (and what I want to do can be done with spot using several playbooks))

I think that I would prefer the default behaviour that only the task called `default` is executed. This will be consistent with the existing logic of the targets. (and, probably, there should be a way to run all the tasks, something like "--task=all")
