### DISCUSSION TITLE
cond abilities with variables and `/bin/sh -c` wrapping

### DISCUSSION THREAD

**Discussion by dstull** [umputun/spot#237] [Q&A] [answered]
I am experiencing some limitations in what I believe is the ability of the `cond` feature. See https://gitlab.com/gitlab-com/support/support-team-meta/-/issues/6488#note_2251568589 for more details on specific use/context.

Here is my current playbook file

```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa                # ssh key
ssh_shell: /bin/bash
local_shell: /bin/bash
inventory: inventory.yml

tasks:
  - name: Check known rails issues
    targets: ["gitlab_rails"]
    commands:
      - name: 366450
        script: |
          echo "Checking condition for known issue 366450"
          grep -s 'OmniAuth::Strategies::SAML' /etc/gitlab/gitlab.rb | grep strategy_class
          if [ $? -eq 0 ]; then
            echo "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
            echo "Make sure your SAML provider is configured with 'saml' as name."
          fi
        options: {ignore_errors: true, sudo: true}
        cond: "version=${GITLAB_VERSION//./}; [[ $version -gt 1500 && $version -lt 1630 ]]"
```

When running it I get this output:

```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:1600 -vvv
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[omnibus localhost:22] run task "Check known rails issues", commands: 2
[omnibus localhost:22] run command "366450"
[omnibus localhost:22]  > sudo /bin/sh -c "/bin/bash -c 'export GITLAB_VERSION=\"1600\"; version=${GITLAB_VERSION//./}; [[ $version -gt 1500 && $version -lt 1630 ]]'"
[omnibus localhost:22]  ! /bin/bash: -c: line 0: conditional binary operator expected
[omnibus localhost:22]  ! /bin/bash: -c: line 0: syntax error near `1500'
[omnibus localhost:22]  ! /bin/bash: -c: line 0: `export GITLAB_VERSION="1600"; version=; [[  -gt 1500 &&  -lt 1630 ]]'
[omnibus localhost:22] completed command "366450" {skip: 366450} (979ms)
```

The issue here seems to be around variable use ENV or otherwise and referencing it when double wrapped in `/bin/sh -c`.

In other words, the below works fine:

```console
sudo /bin/bash -c 'export GITLAB_VERSION="1600"; version=${GITLAB_VERSION//./}; [[ $version -gt 1500 && $version -lt 1750 ]]'
```

Also if I were to try and correctly escape this with it still being wrapped in `/bin/sh -c` with:

```console
ubuntu@sr-env-049aca04-omnibus:~$ sudo /bin/sh -c "/bin/bash -c 'export GITLAB_VERSION=1600; version=\${GITLAB_VERSION//./};[[ \$version -gt 1500 && \$version -lt 1750 ]]'"
ubuntu@sr-env-049aca04-omnibus:~$
```

That works fine, but when I translate that into the playbook it doesn't pass the file validation check:

entry in yml:

`cond: "version=\${GITLAB_VERSION//./};[[ \$version -gt 1500 && \$version -lt 1630 ]]"`

output:

 ```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:1600 -vvv
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
failed, can't get playbook "rails_known_issues.yml": can't load playbook "rails_known_issues.yml": can't unmarshal config: 2 errors occurred:
	* can't unmarshal yaml playbook (full mode) rails_known_issues.yml: yaml: line 20: found unknown escape character
	* can't unmarshal yaml playbook (simple mode) rails_known_issues.yml: yaml: line 20: found unknown escape character
```

I was wondering if there was any suggestions here or if we should consider unwrapping the outer `/bin/sh -c` from the `cond`? Or perhaps treat `cond` more like a multi-line script and merely execute it as a temporary script?  Thoughts/suggestions?
