### DISCUSSION TITLE
echo: command doesn't seem to be echo'd anywhere

### DISCUSSION THREAD

**Discussion by dstull** [umputun/spot#238] [Q&A] [answered]
the echo command, nor using an echo in a script: outputs to the console. Am I doing something wrong? 

 See below:

### echo as a command:

- yml setup:

```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa
ssh_shell: /bin/bash
local_shell: /bin/bash
inventory: inventory.yml

tasks:
  - name: Check known rails issue 366450
    targets: ["gitlab_rails"]
    commands:
      - name: Display warning message
        echo: "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
```

- output:

```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:16.0.0
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[omnibus localhost:22] run task "Check known rails issue 366450", commands: 1
[omnibus localhost:22] completed command "Display warning message" {echo: If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450} (927ms)
[omnibus localhost:22] completed task "Check known rails issue 366450", commands: 1 (982ms)
```

### `echo` in a script:

- yml setup:

```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa

targets: ["localhost:22"]
task:
  - name: Check known rails issue 366450
    echo: "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
```

- output:

```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:16.0.0
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[localhost:22] run task "default", commands: 1
[localhost:22] completed command "Check known rails issue 366450" {echo: If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450} (458ms)
[localhost:22] completed task "default", commands: 1 (511ms)
```

I expected the echo output would show the actual echo instead this appears as just a statement of the command being issued, not a actual echo to the console.

**Comment by umputun** [comment]
Confused. It is not just a statement but the actual output to stdout.  If your echo using any vars it will resolve them and print values.
. It follows the same convention as any other command and prints an echo message like you showed above, i.e. `{echo: If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450}`.

I'm not really sure what you expected to see here. Just echo without a command? Or keep the command but without the echo section? Or the command itself and echo on separate lines?

**Reply by dstull** [reply]
@umputun for the `echo:` command my confusion comes when I use it in combination with `cond:` in a config like the below:

```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa
ssh_shell: /bin/bash
local_shell: /bin/bash
inventory: inventory.yml

tasks:
  - name: Check known rails issue 366450
    targets: ["gitlab_rails"]
    commands:
      - name: Condition check
        script: |
          rm -f /tmp/366450
          version=${GITLAB_VERSION//./}
          if [[ $version -gt 1500 && $version -lt 1630 ]]; then
            touch /tmp/366450
          fi
      - name: Checking for known issue
        script: |
          if grep -s 'OmniAuth::Strategies::SAML' /etc/gitlab/gitlab.rb | grep strategy_class; then
            touch /tmp/366450_warning
          fi
        on_exit: "rm -fv /tmp/366450"
        options: {ignore_errors: true, sudo: true}
        cond: "test -f /tmp/366450"
      - name: Display warning message
        echo: "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
        on_exit: "rm -fv /tmp/366450_warning"
        cond: "test -f /tmp/366450_warning"
```

In that config the last command is an echo that I only want to execute if the `cond` passes.

Even if the `cond` doesn't pass, I still see that format of `echo` in the output as seen below. That is surprising to me. If that is expected, perhaps I should change my question here. I want to output to the console a statement only if a condition is met. How might I do that?  The config above should help show my context.

```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:16.0.0
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[omnibus localhost:22] run task "Check known rails issue 366450", commands: 3
[omnibus localhost:22] completed command "Condition check" {script: /bin/sh -c [multiline script]} (1.027s)
[omnibus localhost:22] completed command "Checking for known issue" {script: /bin/sh -c [multiline script]} (121ms)
[omnibus localhost:22] completed command "Display warning message" {echo: If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450} (6ms)
[omnibus localhost:22] completed task "Check known rails issue 366450", commands: 3 (1.211s)
```

**Reply by umputun** [reply]
ah, I have missed cond part. Will take a look

**Reply by umputun** [reply]
for now you could likely just use `script: echo "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"` instead. it will be executed on condition only

**Reply by dstull** [reply]
@umputun  sadly that didn't work for me either and is the `echo in a script` part of my initial.

See config where I changed (first task echo should not show and the 2nd should)

I do see the basically just an echo of the entire script and not a true 'echo'

```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa
ssh_shell: /bin/bash
local_shell: /bin/bash
inventory: inventory.yml

tasks:
  - name: Check known rails issue 366450
    targets: ["gitlab_rails"]
    commands:
      - name: Condition check
        script: |
          rm -f /tmp/366450
          version=${GITLAB_VERSION//./}
          if [[ $version -gt 1500 && $version -lt 1630 ]]; then
            touch /tmp/366450
          fi
      - name: Checking for known issue
        script: |
          if grep -s 'OmniAuth::Strategies::SAML' /etc/gitlab/gitlab.rb | grep strategy_class; then
            touch /tmp/366450_warning
          fi
        on_exit: "rm -fv /tmp/366450"
        options: {ignore_errors: true, sudo: true}
        cond: "test -f /tmp/366450"
      - name: Display warning message
        script: echo "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
        cond: "test -f /tmp/366450_warning"
      - name: Cleanup temp files
        script: |
          rm -fv /tmp/366450_warning
        options: {ignore_errors: true, sudo: true}
  - name: Fake issue that will fail
    targets: ["gitlab_rails"]
    commands:
      - name: Condition check
        script: |
          rm -f /tmp/fake
          version=${GITLAB_VERSION//./}
          if [[ $version -gt 1500 && $version -lt 1700 ]]; then
            touch /tmp/fake
          fi
      - name: Checking condition for known fake issue
        script: |
          if grep -s "gitlab_backup_cli\['dir'\]" /etc/gitlab/gitlab.rb | grep '/var/opt/gitlab/backups'; then
            touch /tmp/fake_warning
          fi
        on_exit: "rm -fv /tmp/fake"
        options: {ignore_errors: true, sudo: true}
        cond: "test -f /tmp/fake"
      - name: Display warning message
        script: echo "If this is set to backups, that is wrong. Make sure you fix that."
        cond: "test -f /tmp/fake_warning"
      - name: Cleanup temp files
        script: |
          rm -fv /tmp/fake_warning
        options: {sudo: true}
```

- output:

```console
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:16.0.0
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[omnibus localhost:22] run task "Check known rails issue 366450", commands: 4
[omnibus localhost:22] completed command "Condition check" {script: /bin/sh -c [multiline script]} (723ms)
[omnibus localhost:22] completed command "Checking for known issue" {script: /bin/sh -c [multiline script]} (91ms)
[omnibus localhost:22] completed command "Display warning message" {skip: Display warning message} (5ms)
[omnibus localhost:22] completed command "Cleanup temp files" {script: /bin/sh -c [multiline script]} (35ms)
[omnibus localhost:22] completed task "Check known rails issue 366450", commands: 4 (912ms)
[omnibus localhost:22] run task "Fake issue that will fail", commands: 4
[omnibus localhost:22] completed command "Condition check" {script: /bin/sh -c [multiline script]} (228ms)
[omnibus localhost:22] completed command "Checking condition for known fake issue" {script: /bin/sh -c [multiline script]} (57ms)
[omnibus localhost:22] completed command "Display warning message" {script: /bin/bash -c 'export GITLAB_VERSION="16.0.0"; echo "If this is set to backups, that is wrong. Make sure you fix that."'} (10ms)
[omnibus localhost:22] completed command "Cleanup temp files" {script: /bin/sh -c [multiline script]} (35ms)
[omnibus localhost:22] completed task "Fake issue that will fail", commands: 4 (389ms)
```

I guess what I expected to see instead of:

```console
[omnibus localhost:22] completed command "Display warning message" {script: /bin/bash -c 'export GITLAB_VERSION="16.0.0"; echo "If this is set to backups, that is wrong. Make sure you fix that."'} (10ms)
```

was something like this that might stand out more...

```console
[omnibus localhost:22] If this is set to backups, that is wrong. Make sure you fix that
```

What I'm looking for here is a way to notify to the console in a clear way things that fail a check... yet I want execution to continue through all checks.

Is there a way to do that/am I missing something?
