### DISCUSSION TITLE
The logic for specifying target from command line

### DISCUSSION THREAD

**Discussion by bessarabov** [umputun/spot#31] [General]
I'm not sure that I understand all the ideas behind the command line options that are used to specify the list of hosts where to execute the code.

The basic things I think that I understand correctly:

 * if nothing about the targets is specified in the command line options, then the `default` target from playbook will be used (and if there is no `default` target in playbook the spot will immediately  stop)
 * If you specify one ore more `--target` then only the specified targets will be used. The value of `--target` can be:
     1. the name of the target from playbook — that name can "expand" to one host, or several hosts, depending what is written in playbook
     2. the hostname without port `--target=host.example.com` (this will use default ssh port 22)
     3. the hostname with port `--target=host.example.com:1122`
     
But other than that I don't think that I understand other use cases of the system.

## 1

Is it correct that currently there is no way to specify user for every host in target?

For example, I want to run ad-hoc command on several hosts that are not described in inventory and are not written in playbook.

```
h1.example.com is working with user1
h2.example.com is working with user2
h3.example.com is working with user3
```

What do you think of allowing json as a value for target?

```
spot --target={"host":"h1.example.com", "user": "user1"} --target={"host":"h2.example.com", "user": "user2"} --target={"host":"h3.example.com", "user": "user3"} --cmd date
```

## 2

Now I specify several `--targets` and it works as I expect. But it is not working when I try to specify several --inventory-file`.

```
spot --inventory-file=inventory1.yaml --inventory-file=inventory2.yaml --cmd date
```

I expect this to run the ad-hoc command on all the hosts that are in `inventory1.yaml ` & `inventory2.yaml ` (currently spot does not show the error for such command, but it takes only hosts from `inventory2.yaml`)

## 3

Currently it is allowed to specify the `--inventory-file` and the `--target` at the same time but it does is not working the way I expect it to work.

```
spot --inventory-file=inventory.yaml --target=h1.example.com --cmd date
```
I expect this command to fail with the error "can't specify --target & --inventory-file" or to be executed on all hosts in `inventory.yaml` file and on the host `h1.example.com`, but `spot` runs command only on the hosts from inventory file.

## 4

The is a new option `--filter`, from the docs:

> `--filter`, `-f`: Set the allowed hosts using the provided name or host address. This flag acts as a filter for the hosts defined in the playbook file or inventory. For instance, if a user has a playbook file with 10 hosts but only wants to execute the tasks on 3 of them, the `--filter` flag can be used to specify (filter) the desired host names and host addresses to execute the tasks on. Example usage: `--filter=h1.example.com --filter=h2.example.com -f=my-cool-host`.

It is really needed? If one needs to work only with 3 hosts why not to use:

```
--target=h1.example.com --target=h2.example.com --target=my-cool-host.example.com
```

or to create separate inventory file with only needed hosts?

PS I didn't checked `--inventory-url`, but I think that all that I've written about `--inventory-file` is working the same way for `--inventory-url`

**Comment by umputun** [comment]
I just thought about the unhealthy mix between inventory and destinations, targets, and filters and found it confusing. Thinking of simplifying it  a  little bit

This is  the  proposed change:

```yml
user: app
ssh_key: ~/.ssh/id_rsa
inventory: /etc/spot/inventory.yml  # can be a file name or link here.  env SPOT_INVENTORY sets it if nothing is defined  in playbook,  cli override the highest  priority 

targets:
  prod:
    hosts: [{host: "h1.example.com", port: 2222, user: "app-user"}, {host: "h2.example.com"}] #direct list of host, inventory ignored
  staging:
    groups: ["serversx", "serversy"] # inventory groups, group "all" for all servers from inventory
 
```

The tasks part will stay as is.

in the command line will have a single parameter `--inventory=file|url` enforcing inventory file/url. 

The idea is to separate inventory and destinations/target. So, with --target=name, it will match to inventory's host; with --target=group, it will match the inventory group and with --target=ip/fqdn it will set hosts directly.  We could drop the filter completely because all it does now it limit the list of hosts from the inventory. After the change I'm proposing,  the inventory won't be the actual list of destinations to run on but rather some sort of dictionary.  This is similar to how Ansible treats inventory.

For the usual  playbook run cli will look like  this:

`spot  --playbook=blah.yml  --target=prod  --target=dev` - will  run  playbook  task on all  the hosts defined  for  targets
`spot  --playbook=blah.yml  --target=prod  --target=dev  --inventory=custom.yml` - will use custom.yml as inventory to  handle groups
`sport --playbook=blah.yml --target=example.com` - run playbook on example.com only
`sport --playbook=blah.yml --target=host1` - run playbook  on  a  server defined in inventory  and named `host1`
`sport --playbook=blah.yml  --target=groupname` - run playbook for all servers  in inventory group "groupname"

for  ad-hoc command, it will be very  similar, but we won't be  able to pick target from  the playbook:

`sport --cmd="ls -la /tmp" --target=[example.com|host11| groupname]` - instead  of playbook  run the custom command

 I  think,  this change will simplify things for users and will also make the code more direct. Let me know what you think.

**Reply by umputun** [reply]
Another simplification I thought of is to eliminate the --cmd param and treat the first positional argument as the command, i.e., if it sees the `spot something` where "something" is not a `-x` or `--blah` - this is  the command:

i.e., this will run ad-hoc command `sport "ls -la /srv" --targer=somehost`

**Comment by bessarabov** [comment]
Short answer — I really like your ideas.

Some minor comments and thoughts on your text:
 
 * `inventory: /etc/spot/inventory.yml  # can be a file name or link here` — yes, I think this is a good change
 * `with --target=name, it will match to inventory's host; with --target=group, it will match the inventory group` — so there should be check that there are no duplicate names for names and hosts
 * `eliminate the --cmd param and treat the first positional argument as the command` — really like it

In this description you didn't say anything about the format of file/url inventory, so I assume that it stays the same as it is specified in the current docs, 2 formats:

```
groups:
  dev:
    - {host: "h1.example.com", name: "h1"}
    - {host: "h2.example.com", port: 2233, name: "h2"}
    - {host: "h3.example.com", user: "user1"}
    - {host: "h4.example.com", user: "user2", name: "h4"}
  staging:
    - {host: "h5.example.com", port: 2233, name: "h5"}
    - {host: "h6.example.com", user: "user3", name: "h6"}
```

```
hosts:
  - {host: "hh1.example.com", name: "hh1"}
  - {host: "hh2.example.com", port: 2233, name: "hh2", user: "user1"}
  - {host: "h2.example.com", port: 2233, name: "h2"}
  - {host: "h3.example.com", user: "user1", name: "h3"}
  - {host: "h4.example.com", user: "user2", name: "h4"}
```

In such format there can be a `name` for server, probably that names should be also allowed for specifying the target:

```
targets:
  staging:
    names: ["h1", "h2"]
```

Maybe it should be also allowed to use several ways of getting list of hosts in one target, something like:

```
targets:
  tmp:
    hosts: [{host: "h1.example.com", port: 2222, user: "app-user"}]
    groups: ["staging"]
    names: ["h4"]
```

(this will create target 'tmp' that has host 'h1.example.com', all the hosts from group 'staging' and a host with name 'h4')

But one thing can go wrong here. It is possible to specify one host several times. Probably if such situation occur in configs the `spot` should report for the error in configs and exit. (I can't imagine situation when somebody need to run the same commands on the host several times, but if if future somebody will need it, some new option can be added that should be added to cli to allow this)

(I was also thinking to be able to specify the list of tags in inventory's host definition `{host: "h2.example.com", port: 2233, name: "h2", tags: ["ubuntu_20_04", "db"]}` and the ability to add hosts to the target based by tags, but I'm not sure that this should be added in spot version 1.0, it can be added later)

I would also expect this to work: `spot  --playbook=blah.yml  --target=all` — where `all` is a reserved word that means every host from the inventory (there can't be a group with this name and 'all' can be used as a name for host)

I was thinking if the env variables are really needed. But I think that I really love SPOT_INVENTORY variable — I think that is it very comfortable to set SPOT_INVENTORY and use `spot` for ad-hoc commands, so SPOT_INVENTORY is a good thing.

But I don't like the logic in the playbook `env SPOT_INVENTORY sets it if nothing is defined  in playbook,`, I think that I would prefer to specify empty `inventory: ` in playbook to explicitly say that I'm not using any inventory (I would expect that specifying `inventory: ` will not be overriden by env variable (but can be overriden by cli option))
