### DISCUSSION TITLE
Maybe it is possible to leave only one format for inventory?

### DISCUSSION THREAD

**Discussion by bessarabov** [umputun/spot#45] [General]
Currently there are 2 allowed formats for inventory:

```yaml
groups:
  dev:
    - {host: "h1.example.com", name: "h1", tags:["us-east1", "vpc-1234567"]}
    - {host: "h2.example.com", port: 2233, name: "h2"}
    - {host: "h3.example.com", user: "user1"}
    - {host: "h4.example.com", user: "user2", name: "h4"}
  staging:
    - {host: "h5.example.com", port: 2233, name: "h5"}
    - {host: "h6.example.com", user: "user3", name: "h6"}
```

```yaml
hosts:
  - {host: "hh1.example.com", name: "hh1"}
  - {host: "hh2.example.com", port: 2233, name: "hh2", user: "user1"}
  - {host: "h2.example.com", port: 2233, name: "h2", tags:["us-east1", "vpc-1234567"]}
  - {host: "h3.example.com", user: "user1", name: "h3"}
  - {host: "h4.example.com", user: "user2", name: "h4"}
```

What's the point of the second format? Why anybody need to use the second format? It's easy to put all the hosts in one group, for example:

```yaml
groups:
  group:
    - {host: "hh1.example.com", name: "hh1"}
    - {host: "hh2.example.com", port: 2233, name: "hh2", user: "user1"}
    - {host: "h2.example.com", port: 2233, name: "h2", tags:["us-east1", "vpc-1234567"]}
    - {host: "h3.example.com", user: "user1", name: "h3"}
    - {host: "h4.example.com", user: "user2", name: "h4"}  
```
