### DISCUSSION TITLE
Should all: be in playbook example in README?

### DISCUSSION THREAD

**Discussion by bessarabov** [umputun/spot#51] [General]
Now in README.md there is an example of playbook:

```
targets:
  prod:
    hosts: # list of hosts, user, name and port optional. 
      - {host: "h1.example.com", user: "user2", name: "h1"}
      - {host: "h2.example.com", port: 2222}
  staging:
    groups: ["dev", "staging"] # list of groups from inventory file
  dev:
    names: ["devbox1", "devbox2"] # list of server names from inventory file
  all:
    groups: ["all"] # all hosts from all groups from inventory file
```

I'm not sure if the `all:` is a good example to be placed in playbook. Why anybody needs to define `all` in playbook, when cli `--target=all` will always run on everything from inventory?
