### ISSUE TITLE
Wrong leading spaces/identation in yaml/script parsing?

### ISSUE THREAD

**Issue by knutov** [umputun/spot#122]
```
spot --version
spot v1.7.0-33fac8b-2023-06-06T00:48:21Z
```

```yaml
  - name: prom_pass
    commands:
      - name: pass
        script: |
          cat << EOF > /etc/prometheus/prometheus.web.yml
          basic_auth_users:
            admin: $PASS
          EOF
```

```bash
$ cat prom.yml | yq '.tasks[2].commands[0].script' | sed 's/"//g' | sed 's/\\n/\n/g'
```

```
cat << EOF > /etc/prometheus/prometheus.web.yml
basic_auth_users:
  admin: $PASS
EOF
```

```bash
spot -p prom.yml --dbg --dry
```

```
[s2 s2.hidden.tld:22]  ! command script /tmp/.spot/spot-script3829472563
[s2 s2.hidden.tld:22]  > #!/bin/sh
[s2 s2.hidden.tld:22]  > set -e
[s2 s2.hidden.tld:22]  > cat << EOF > /etc/prometheus/prometheus.web.yml
[s2 s2.hidden.tld:22]  > basic_auth_users:
[s2 s2.hidden.tld:22]  > admin: $PASS
[s2 s2.hidden.tld:22]  > EOF
```

There is no leading spaces in `admin: $PASS` line and file created by this script does not contain them too which leads to wrong yaml config.
