### ISSUE TITLE
Wait command doesn't parse on TOML format

### ISSUE THREAD

**Issue by ifraixedes** [umputun/spot#132]
I tried to use the `wait` command on a playbook defined in TOML format and `spot` returns 

```
failed, can't get playbook "test.toml": can't load playbook "test.toml": can't unmarshal config: 1 error occurred:
        * can't unmarshal toml playbook test.toml: toml: cannot decode TOML array table into struct field config.Cmd.Wait of type config.WaitInternal
```

I may be doing something wrong.

This is the example playbook that I executed

```toml
[[tasks]]
name = "wait-test"

[[tasks.commands]]
name = "Check Jenkins CLI required environment variables"
options = { local = true }
[[tasks.commands.wait]]
cmd = "curl --fail --head -s http://localhost:8080"
timeout = "90s"
interval = "3s"
```

I also tried with this one, which should be the same
```toml
[[tasks]]
name = "wait-test"

[[tasks.commands]]
name = "Check Jenkins CLI required environment variables"
options = { local = true }
wait = { cmd = "curl --fail --head -s http://localhost:8080", timeout = "90s", interval = "3s" }
```

If I execute the "same" playbook in YAML format, I don't get any error:

```yaml
tasks:
  - name: wait-test
    commands:
      - name: Check Jenkins CLI required environment variables
        options: {local: true}
        wait: {cmd: "curl --fail --head -s http://localhost:8080", timeout: "90s", interval: "3s"}
```

or the same one with `wait` being spread along the lines

```yaml
tasks:
  - name: wait-test
    commands:
      - name: Check Jenkins CLI required environment variables
        options:
          local: true
        wait:
          cmd: curl --fail --head -s http://localhost:8080
          timeout: 90s
          interval: 3s
```

**Comment by umputun** [comment]
I'm not an expert in toml and don't use it much, but converting the yml above to toml with https://www.convertsimple.com/convert-yaml-to-toml/ produced this:

```toml
[[tasks]]
name = "wait-test"

  [[tasks.commands]]
  name = "Check Jenkins CLI required environment variables"

    [tasks.commands.options]
    local = true

    [tasks.commands.wait]
    cmd = "curl --fail --head -s http://localhost:8080"
    timeout = "90s"
    interval = "3s"
```

This toml is better; however still not good as it fails with `can't unmarshal toml playbook spot.toml: toml: cannot store TOML string into a Go int64`. It looks like toml library is not smart enough to parse the duration present as "90s" or "3s". And this is the [ticket I've found](https://github.com/pelletier/go-toml/issues/767) and a possible workaround. 

Pls note: as of now, toml is sort of a bastard child in the `spot` ;) The provided support is very basic, and it doesn't handle "dynamic" parsing properly, i.e. neither "simple task" format nor optional "list format" for copy, sync, and delete are supported. All of this is implemented for yml [custom parser only](https://github.com/umputun/spot/blob/4ee03460d8b8938495417673625d7ebad3bc6559/pkg/config/command.go#L278-L278)
