### ISSUE TITLE
Bug with parser?

### ISSUE THREAD

**Issue by knutov** [umputun/spot#144]
Split from https://github.com/umputun/spot/discussions/135

With latest spot 1.9.2 there is something wrong with generated shell script:

```yaml
      - name: shell
        script: |-
          f() { export S=passed; }
          f
          # one more line
```

`spot --task=bash  -p test.yml -t s2 --dry` converts it to:

![изображение](https://github.com/umputun/spot/assets/255869/00b5f529-32f8-44cf-8705-e21197303975)

But if I use longer names for function it works as expected:

```yaml
      - name: shell
        script: |-
          f123() { export S=passed; }
          f123
          # one more line
```

![изображение](https://github.com/umputun/spot/assets/255869/35e33723-602a-4fe4-912b-ebc57fca9802)

this way is also works:

```yaml
      - name: shell
        script: |-
          f() { export S=passed; }
          f # make string longer
```

![изображение](https://github.com/umputun/spot/assets/255869/8348f101-d1c3-49b5-88ae-e6b11fe92401)

but removing bash comment inside string field (not yaml itself) is very unexpected behavior. Does spot use some standard lib for yaml processing or some custom lib?
