### ISSUE TITLE
bug with local:true in 1.11.1

### ISSUE THREAD

**Issue by knutov** [umputun/spot#153]
```yaml

  - name: uptime0
    commands:

      - name: first command
        script: |
          export FILE_NAME=/tmp/file1
          touch $FILE_NAME ; ANOTHER_VAR=foo
        # register: [FILE_NAME, ANOTHER_VAR]
        options:
          local: true

      - name: second command
        script: |
          echo "File name is $FILE_NAME, var is $ANOTHER_VAR"
        options:
          local: true
```

Note - both tasks are `local:true`.

![изображение](https://github.com/umputun/spot/assets/255869/ce648701-2c6d-42fa-9615-9f96bf9c70bb)
