### ISSUE TITLE
Documentation clarification (or bug?)

### ISSUE THREAD

**Issue by knutov** [umputun/spot#154]
https://github.com/umputun/spot/blob/509ce88dd16a9cd2b0eced6b233cc94e2b8be779/README.md?plain=1#L735

This looks like named task, but the similar code is not working:

```yaml
tasks:
  t1:
    commands:
      - name: print
        echo: "hello world"
        options:
          local: true

  t2:
    commands:
      - echo: "hello world 2"
        options:
          local: true
```

```text
spot -p test2.yml --task=t2  -t s2

spot v1.11.4-509ce88-2023-08-10T19:03:12Z
failed, can't get playbook "test2.yml": can't load playbook "test2.yml": can't unmarshal config: 2 errors occurred:
        * can't unmarshal yaml playbook (full mode) test2.yml: yaml: unmarshal errors:
  line 15: cannot unmarshal !!map into []config.Task
        * can't unmarshal yaml playbook (simple mode) test2.yml: yaml: unmarshal errors:
  line 10: cannot unmarshal !!map into []string
  line 13: field tasks not found in type config.SimplePlayBook
```

So, is it supposed to be working the same as 

```yaml
tasks:
  - name: t1
...
  - name: t2
...
```

or is it mistake in documentation?
