### ISSUE TITLE
export + env: possible bug

### ISSUE THREAD

**Issue by knutov** [umputun/spot#155]
## Strange case with double export the same var

```yaml
ssh_shell: /bin/bash
...
tasks:
  # spot -p test.yml --task=etest
  - name: etest
    commands:
      - script: export H=123
      - echo: $H
        options: { local: true }
      - script: export H="$H 321"
        env: { H: $H }
      - echo: $H
        options: { local: true }
```

expected result in second print is "123 321" but it is "123". But it works as expected if in second export/echo I change variable name (from H to X for example). Should it be so?

## Strange case with reuse exported var vs passing const value

```yaml
  - name: etest2
    commands:
      - script: export X=123
      - echo: $X
        options: { local: true }
      - script: export H="$X 321"
        env: { X: $X }
      - echo: $H
        options: { local: true }
```

This will result to "123" and "321". But...

```yaml
  - name: etest2
    commands:
      - script: export X=123
      - echo: $X
        options: { local: true }
      - script: export H="$X 321"
        env: { X: 123 } # <---------
      - echo: $H
        options: { local: true }
```

results to "123" and "123 321" which is also very strage and unexpected/unpredictable.

Is this behavior intended?
