### ISSUE TITLE
Local command actually runs in dry mod

### ISSUE THREAD

**Issue by rahfar** [umputun/spot#174]
Hello,

I have such example playbook at `spot.yml`:

```yaml
user: root
ssh_key: ~/.ssh/id_rsa
ssh_shell: /bin/bash
local_shell: /bin/bash

tasks:
  - name: local
    commands:
      - script: echo 123
        options:
          local: true
      - script: imaginarycmd
        options:
          local: true

```

output of `spot -v --dry`:
```
spot v1.13.1-31e622d-2024-02-13T18:19:02Z
dry run - no changes will be made and no commands will be executed
[localhost] run task "local", commands: 2 (local)
[localhost] run command ""
[localhost]  > echo 123
[localhost]  > 123
[localhost] completed command "" {script: /bin/bash -c 'echo 123'} (0s)
[localhost] run command ""
[localhost]  > imaginarycmd
[localhost]  ! /bin/bash: line 1: imaginarycmd: command not found
[default]  ! failed command "" on host default:22 (): can't run script on default:22: exit status 127
failed, can't run task "local" for target "default": 1 error(s) occurred:
   [0] failed command "" on host default:22 (): can't run script on default:22: exit status 127

```

I was expecting that dry mode would not run both remote and local commands (and now it does not run only remote) - am I wrong at this point?

PS Thanks for project, like it more than ansible
