### ISSUE TITLE
Task level user setting looks not working, docs mistake

### ISSUE THREAD

**Issue by rahfar** [umputun/spot#192]
Hello,

Noticed that in docs section https://spot.umputun.dev/#playbook-types said that I can specify `ssh_key`:  

> The simplified playbook does not support task-level on_error, user, and ssh_key fields, while the full playbook does. See the [Task details](https://spot.umputun.dev/#tasks-and-commands) section for more information.

But link leads to https://spot.umputun.dev/#tasks-and-commands, where it is said that only 3 of 4 fields are available: `on_error`, `user`, `targets`.

Actually I am trying to config my playbook to have 2 tasks, each on different remote. Here is playbook:
```yaml
ssh_key: ~/.ssh/id_rsa

tasks:
  - name: t1
    user: "user1"
    targets:
      - "host2"
    commands:
      - name: test
        script: echo hello, world!

  - name: t2
    user: "user2"
    targets:
      - "host2"
    commands:
      - name: test
        script: echo hello, world!

```

But it is not working. If I specify user=user1 on playbook level, then t1 is working and t2 crashes with
```
failed, can't run task "t2" for target "***": 1 error(s) occurred:
   [0] can't connect to ***: failed to create client connection to ***:22: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
Obviously, because of wrong user selection

Also it is not clear if `ssh_key` is supported on task level?

Currently my workaround is to have 2 separate playbooks for each host

**Comment by rahfar** [comment]
Maybe I am wrong, but here looks like the root of the problem:
https://github.com/umputun/spot/blob/c9fd18516ee32ca111afb1ab1fcc893f38489eb9/pkg/runner/runner.go#L91

should it be `tsk.User`, rather than `host.User`?

**Comment by umputun** [comment]
just to clarify if this is not a typo in your playbook before I go any deeper - you said "... playbook to have 2 tasks, each on different remote" however the playbook you provided runs both tasks on the same `host2`

**Comment by rahfar** [comment]
Yup, this is a typo, I meant host1 and host2, of course

**Comment by umputun** [comment]
so, I would assume it fails with a correct host, right? If this is the case, I'll take a look.

in the meantime, you can specify top-level targets and set the user here, i.e.
```
targets:
  dev:
    hosts:
      - {name: "dev1", host: "dev1.example.com", port: 22, user: user1}
      - {name: "dev2", host: "dev2.example.com", port: 22, user: user2}

tasks:
  - name: t1
    targets:
      - "dev1"
    commands:
      - name: test
        script: echo hello, world!

  - name: t2
    targets:
      - "dev2"
    commands:
      - name: test
        script: echo hello, world!
```
