### ISSUE TITLE
Change behavior of `register` directive to apply it to all following tasks

### ISSUE THREAD

**Issue by umputun** [umputun/spot#196]
currently, exporting a var or setting them to `register` acts the same way - making the var available for other commands in the given task. I think this is the correct logic for set var, but incorrect for `register`. The proposed change will update all the following tasks by injecting register vars into them.

see https://github.com/umputun/spot/discussions/195#discussioncomment-9243672 for more details

**Comment by umputun** [comment]
@koolay - the change in place on the :master image. Pls, give it a try and see if it fixes the reported issue

**Comment by koolay** [comment]
Hi, it is not work when target host is not on the same host.
@umputun

**Comment by umputun** [comment]
The change shouldn't be tied to any target host but rather propagate it to all the tasks. If it doesn't work for you, please provide the playbook and output of the spot with --dbg and -v.

This is the one I have tested and it worked as expected:

```yml
user: umputun
ssh_key: ~/.ssh/id_rsa

targets:
  dev1:
    hosts: [{host: "dev1.umputun.dev", name: "dev1"}]
  dev2:
    hosts: [{host: "dev2.umputun.dev", name: "dev2"}]

tasks:
  - name: first
    targets: ["dev1"]
    commands:
      - name: get host name
        script: |
            myhost=$(hostname)
        register: [myhost]

  - name: second
    targets: ["dev2"]
    commands:
      - name: show host name
        script: |
            echo "show myhost var: $myhost"
```

```
[dev1 dev1.umputun.dev:22] run task "first", commands: 1
[dev1 dev1.umputun.dev:22] run command "get host name"
[dev1 dev1.umputun.dev:22]  > /bin/sh -c /tmp/.spot-8947750978994702336/spot-script1300844333
[dev1 dev1.umputun.dev:22]  > setvar myhost=dev1.umputun.dev
[dev1 dev1.umputun.dev:22] completed command "get host name" {script: /bin/sh -c [multiline script]} (79ms)
[dev1 dev1.umputun.dev:22] completed task "first", commands: 1 (150ms)
[dev2 dev2.umputun.dev:22] run task "second", commands: 1
[dev2 dev2.umputun.dev:22] run command "show host name"
[dev2 dev2.umputun.dev:22]  > /bin/sh -c 'myhost="dev1.umputun.dev"; echo "show myhost var: $myhost"'
[dev2 dev2.umputun.dev:22]  > show myhost var: dev1.umputun.dev
[dev2 dev2.umputun.dev:22] completed command "show host name" {script: /bin/sh -c 'myhost="dev1.umputun.dev"; echo "show myhost var: $myhost"'} (8ms)
[dev2 dev2.umputun.dev:22] completed task "second", commands: 1 (91ms)
```

As you can see, `myhost` was set on `dev1` and later echoed on `dev2`.
