### ISSUE TITLE
Enviroment variables not working depends how launch the script

### ISSUE THREAD

**Issue by fidojones** [umputun/spot#211]
**Test in version: v1.16.0**

**This not works:**

```
user: root
ssh_shell: /bin/bash

targets:
  prod:
    hosts: # list of hosts, user, name and port optional. 
      - {host: "192.168.1.10", user: "root", name: "h1"}

tasks:
  - name: Some tests
    targets: ["prod"]
    commands:
      - name: Testing enviroment vars
        script: /tmp/test_env.py
        env: {TESTVAR: example-value} # set environment variables for the command
```

spot v1.16.0-ca4ade3-2024-04-27T19:58:38Z
[h1 192.168.1.42:22] run task "Some tests", commands: 1
[h1 192.168.1.42:22] run command "Testing enviroment vars"
[h1 192.168.1.42:22]  > /bin/sh -c 'TESTVAR="example-value"; /tmp/test_env.py'
[h1 192.168.1.42:22]  > The TESTVAR not configured.
[h1 192.168.1.42:22] completed command "Testing enviroment vars" {script: /bin/sh -c 'TESTVAR="example-value"; /tmp/test_env.py'} (57ms)
[h1 192.168.1.42:22] completed task "Some tests", commands: 1 (76ms)

**This works:**

```
user: root
ssh_shell: /bin/bash

targets:
  prod:
    hosts: # list of hosts, user, name and port optional. 
      - {host: "192.168.1.10", user: "root", name: "h1"}

tasks:
  - name: Some tests
    targets: ["prod"]
    commands:
      - name: Testing enviroment vars
        script: |
         /tmp/test_env.py
        env: {TESTVAR: example-value} # set environment variables for the command
```

pot v1.16.0-ca4ade3-2024-04-27T19:58:38Z
dry run - no changes will be made and no commands will be executed
[h1 192.168.1.42:22] run task "Some tests", commands: 1
[h1 192.168.1.42:22] run command "Testing enviroment vars"
[h1 192.168.1.42:22]  ! command script /tmp/.spot-6503112504996233216/spot-script3662322200
[h1 192.168.1.42:22]  > #!/bin/sh
[h1 192.168.1.42:22]  > set -e
[h1 192.168.1.42:22]  > export TESTVAR="example-value"
[h1 192.168.1.42:22]  > /tmp/test_env.py
[h1 192.168.1.42:22]  > /bin/sh -c /tmp/.spot-6503112504996233216/spot-script3662322200
[h1 192.168.1.42:22] completed command "Testing enviroment vars" {script: /bin/sh -c [multiline script]} (0s)
[h1 192.168.1.42:22] completed task "Some tests", commands: 1 (13ms)

The fail example excute this,and if I do this in command line by hand, it doesn't work: 

`/bin/sh -c 'TESTVAR="example-value"; /tmp/test_env.py' `

But **but if I add "export"**, like this: 

`/bin/sh -c 'export TESTVAR="example-value"; /tmp/test_env.py'`

Works fine.

**Comment by umputun** [comment]
I can't reproduce it. Setting env for a single command the way like spot does is a very standard. I'm not sure what part of this is not working in your tests as I don't have the source of `test_env.py`, however i made a simple command like this to simulate your non-working example

```
  - name: single
    commands:
      - name: do something
        script: "echo env_test is $env_test"
        env: {env_test: foo}
```

This runs fine and sets env_test to foo as expected

```
[dev2 dev2.umputun.dev:22] run task "single", commands: 1
2024/06/05 13:02:07.914 [INFO]  run command "do something" on host "dev2.umputun.dev:22" (dev2)
[dev2 dev2.umputun.dev:22] run command "do something"
2024/06/05 13:02:07.914 [DEBUG] execute script "do something" on dev2.umputun.dev:22
2024/06/05 13:02:07.914 [DEBUG] command "do something" is single line, using script string
2024/06/05 13:02:07.914 [DEBUG] run /bin/sh -c 'env_test="foo"; echo env_set is $env_test'
2024/06/05 13:02:07.914 [DEBUG] run ssh command "/bin/sh -c 'env_test=\"foo\"; echo env_set is $env_test'" on 192.168.1.42:22
[dev2 dev2.umputun.dev:22]  > /bin/sh -c 'env_test="foo"; echo env_set is $env_test'
[dev2 dev2.umputun.dev:22]  > env_set is foo
[dev2 dev2.umputun.dev:22] completed command "do something" {script: /bin/sh -c 'env_test="foo"; echo env_set is $env_test'} (4ms)
```
