### ISSUE TITLE
ssh_shell is being ignored inside playbook

### ISSUE THREAD

**Issue by fidojones** [umputun/spot#212]
I have defined ssh_shell: /bin/bash inside playbook, but in verbose mode it show that us /bin/sh to launch:

**Test in version: v1.16.0**

```
user: root
ssh_shell: /bin/bash

targets:
  prod:
    hosts: # list of hosts, user, name and port optional. 
      - {host: "192.168.1.42", user: "root", name: "h1"}

tasks:
  - name: Some tests
    targets: ["prod"]
    commands:
      - name: Testing enviroment vars
        cond: "test -f /tmp/test_env.py"
        script: |
         /tmp/test_env.py
        env: {TESTVAR: example-value} # set environment variables for the command
```

`spot -p test-env.yml -v --dry`

spot v1.16.0-ca4ade3-2024-04-27T19:58:38Z
dry run - no changes will be made and no commands will be executed
[h1 192.168.1.42:22] run task "Some tests", commands: 1
[h1 192.168.1.42:22] run command "Testing enviroment vars"
[h1 192.168.1.42:22]  > **/bin/sh -c 'TESTVAR="example-value"; test -f /tmp/test_env.py'**
[h1 192.168.1.42:22]  ! command script /tmp/.spot-719631138223510784/spot-script4222649707
[h1 192.168.1.42:22]  > #!/bin/sh
[h1 192.168.1.42:22]  > set -e
[h1 192.168.1.42:22]  > export TESTVAR="example-value"
[h1 192.168.1.42:22]  > /tmp/test_env.py
[h1 192.168.1.42:22]  > **/bin/sh -c /tmp/.spot-719631138223510784/spot-script4222649707**
[h1 192.168.1.42:22] completed command "Testing enviroment vars" {script: /bin/sh -c [multiline script]} (0s)
[h1 192.168.1.42:22] completed task "Some tests", commands: 1 (21ms)

If I call it in the command line works fine:

`spot -p test-env.yml -v --dry --shell /bin/bash`

spot v1.16.0-ca4ade3-2024-04-27T19:58:38Z
dry run - no changes will be made and no commands will be executed
[h1 192.168.1.42:22] run task "Some tests", commands: 1
[h1 192.168.1.42:22] run command "Testing enviroment vars"
[h1 192.168.1.42:22]  > **/bin/bash -c 'TESTVAR="example-value"; test -f /tmp/test_env.py'**
[h1 192.168.1.42:22]  ! command script /tmp/.spot-7313637980666303488/spot-script1822616870
[h1 192.168.1.42:22]  > #!/bin/bash
[h1 192.168.1.42:22]  > set -e
[h1 192.168.1.42:22]  > export TESTVAR="example-value"
[h1 192.168.1.42:22]  > /tmp/test_env.py
[h1 192.168.1.42:22]  > **/bin/bash -c /tmp/.spot-7313637980666303488/spot-script1822616870**
[h1 192.168.1.42:22] completed command "Testing enviroment vars" {script: /bin/bash -c [multiline script]} (0s)
[h1 192.168.1.42:22] completed task "Some tests", commands: 1 (15ms)
