### ISSUE TITLE
Targets excution

### ISSUE THREAD

**Issue by polderudo** [umputun/spot#228]
I'm running into a problem with the evaluation of a target. Following script
```
ssh_key: ~/.ssh/deploy_rsa.private
local_shell: /bin/bash

targets:
  stage:
    hosts: [{host: "stage.server", user: "user", port: 666}]
  prod:
    hosts: [{host: "localhost"}]

tasks:
  - name: set global-vars
    options: {local: true}
    commands:
      - name: set global vars
        script: |
          BINARY_NAME=app         
          FRONTEND_LOCAL_DIR=frontend
          SRV_FILE_NAME=$(date '+%Y-%m-%d--%H.%M.%S').$BINARY_NAME
        register: [ BINARY_NAME,FRONTEND_LOCAL_DIR, SRV_FILE_NAME ]

  - name: set vars-stage
    targets: ["stage"]
    options: {local: true}
    commands:
      - name: set stage-vars
        script: |
          SUPERVISOR_NAME=em
          SERVER_DIR=/srv/app
          NODE_BUILD_TARGET=build
        register: [SERVER_DIR,NODE_BUILD_TARGET, SUPERVISOR_NAME]
        #options: {local: true}

  - name: set vars-prod
    targets: [ "prod" ]
    options: {local: true}
    commands:
      - name: set prod-vars
        script: |          
          NODE_BUILD_TARGET=build
        register: [NODE_BUILD_TARGET]

  - name: build vue
    options: {local: true}
    commands:
      - name: del dist folder
        script: rm -rf $FRONTEND_LOCAL_DIR/dist
      - name: build vue
        script: |
          #!/bin/bash
          . ~/.bashrc
          cd $FRONTEND_LOCAL_DIR
          nvm use
          npm run $NODE_BUILD_TARGET

  - name: build go
    options: {local: true}
    commands:
      - name: create binary
        script: make build-linux

  - name: manage server
    targets: ["stage"]
    options: {only_on: [stage]}
    commands:
      - name: copy to server
        copy: { "src": "$BINARY_NAME", "dst": "$SERVER_DIR/versions/$SRV_FILE_NAME" }

      - name: change sym-link to current version
        script: ln -fsn $SERVER_DIR/versions/$SRV_FILE_NAME $SERVER_DIR/$BINARY_NAME

      - name: migrate db
        script: |
          cd $SERVER_DIR 
          ./$BINARY_NAME migrate up

      - name: restart app
        script: |
          supervisorctl restart $SUPERVISOR_NAME  
```

So pretty basic one. 2 targets stage and prod. But somehow the last tast "manage server" is also called for prod target:
```
[localhost] completed task "build go", commands: 1 (1.82s)
failed, can't run task "manage server" for target "prod": 1 error(s) occurred:
   [0] failed to dial: dial tcp [::1]:22: connect: connection refused

```

Am i doing something wrong here? With targets: ["stage"] "manage server" should not be called at all right?
