### ISSUE TITLE
temporary script files aren't being cleaned up

### ISSUE THREAD

**Issue by umputun** [umputun/spot#242]
### Discussed in https://github.com/umputun/spot/discussions/239

<div type='discussions-op-text'>

<sup>Originally posted by **dstull** December 18, 2024</sup>
It seems my temporary script files aren't being deleted....even though I see a `teardown` in the code.

Is there something I'm missing or doing wrong?

- config:
```yml
user: ubuntu
ssh_key: /home/ubuntu/.ssh/id_rsa
ssh_shell: /bin/bash
local_shell: /bin/bash
inventory: inventory.yml

tasks:
  - name: Check known rails issue 366450
    targets: ["gitlab_rails"]
    commands:
      - name: Condition check
        script: |
          rm -f /tmp/366450
          version=${GITLAB_VERSION//./}
          if [[ $version -gt 1500 && $version -lt 1630 ]]; then
            touch /tmp/366450
          fi
      - name: Checking for known issue
        script: |
          if grep -s 'OmniAuth::Strategies::SAML' /etc/gitlab/gitlab.rb | grep strategy_class; then
            touch /tmp/366450_warning
          fi
        on_exit: "rm -fv /tmp/366450"
        options: {ignore_errors: true, sudo: true}
        cond: "test -f /tmp/366450"
      - name: Display warning message
        echo: "If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450"
        on_exit: "rm -fv /tmp/366450_warning"
        cond: "test -f /tmp/366450_warning"
```

- run output:
```console
ubuntu@sr-env-049aca04-omnibus:~$ ls -ltr /tmp/spot*
ls: cannot access '/tmp/spot*': No such file or directory
ubuntu@sr-env-049aca04-omnibus:~$ ./spot -p rails_known_issues.yml --env GITLAB_VERSION:16.0.0
spot v1.16.1-3c62f53-2024-10-23T16:26:56Z
[omnibus localhost:22] run task "Check known rails issue 366450", commands: 3
[omnibus localhost:22] completed command "Condition check" {script: /bin/sh -c [multiline script]} (1.027s)
[omnibus localhost:22] completed command "Checking for known issue" {script: /bin/sh -c [multiline script]} (121ms)
[omnibus localhost:22] completed command "Display warning message" {echo: If you're using SAML for OmniAuth you might be running into known issue https://gitlab.com/gitlab-org/gitlab/-/issues/366450} (6ms)
[omnibus localhost:22] completed task "Check known rails issue 366450", commands: 3 (1.211s)
ubuntu@sr-env-049aca04-omnibus:~$ ls -ltr /tmp/spot*
-rwx------ 1 ubuntu ubuntu 176 Dec 18 20:08 /tmp/spot-script4216482464
-rwx------ 1 ubuntu ubuntu 172 Dec 18 20:08 /tmp/spot-script897356897
ubuntu@sr-env-049aca04-omnibus:~$
```</div>
