### ISSUE TITLE
Unexpected execution of all tasks despite target filtering 

### ISSUE THREAD

**Issue by skar404** [umputun/spot#249]
When running spot with a specific target (e.g., spot -t prod), all tasks are executed, including those not assigned to the specified target. This behavior appears to ignore the target filtering defined in the configuration.

I’m wondering if this is expected behavior or if I might have a configuration issue. Could you confirm if this behavior is correct, or suggest adjustments to the configuration?

### Example Configuration:
```yaml
ssh_key: keys/id_ed25519

targets:
  prod:
    hosts: [{ host: "public-vpn", user: "root" }]

  dev:
    hosts: [{ host: "public-vpn.dev", user: "root" }]

tasks:
  - name: config prod node
    targets: ["prod"]
    commands:
      - name: command1
        script: echo "Prod Hello World"

  - name: config dev node
    targets: ["dev"]
    commands:
      - name: command_2
        script: echo "Dev Hello World"
 ```
 
### Bash:

```bash
> spot -t prod
spot v1.16.3-54baca2-2024-12-20T23:47:00Z
[public-vpn:22] run task "config prod node", commands: 1
[public-vpn:22] completed command "command1" {script: /bin/sh -c 'echo "Prod Hello World"'} (1s)
[public-vpn:22] completed task "config prod node", commands: 1 (3.126s)
[public-vpn:22] run task "config dev node", commands: 1
[public-vpn:22] completed command "command_2" {script: /bin/sh -c 'echo "Dev hello World"'} (786ms)
[public-vpn:22] completed task "config dev node", commands: 1 (3.018s)
```
