### ISSUE TITLE
line replacement for files

### ISSUE THREAD

**Issue by umputun** [umputun/spot#251]
the task like this appears to be common:

```
  commands:
      - name: "remove source ~/base16.rc from bashrc"
        script: |
          sed -i '/source ~\/base16.rc/d' ~/.bashrc

      - name: "update bashrc with ps1.rc"
        script: |
          echo 'source ~/.config/ps1.rc' >> ~/.bashrc
        cond: "! grep -q 'ps1.rc' ~/.bashrc"
```

Both commands here are sort of similar, updating/removing lines from a file. Maybe we should introduce a new command type allowing achieving the same result but in simpler way.

maybe something like this:

- `line: {file:  "~/.bashrc", match: "^source base16.rc", delete: true}` : delete the line with matched regex
- `line: {file:  "~/.bashrc", match: "^source base16.rc", replace: "something new"}`: replace the line with matched regex
- `line: {file:  "~/.bashrc", match: "^source base16.rc", append: "something else"}`: add the line if match found/not-found

We can also do match and replace for regex groups; however, I'm not sure how useful this would be.

_Just an idea for now, but if you like it and want to implement it, it shouldn't be hard._
