### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by zonescape** [umputun/spot#256]
Is this intentional behavior or a bug?

Currently environment variables are eligible for shell parameter expansion. For example, this task gives string "xxxyyy":

```yaml
task:
  - name: prints xxxyyy
    script: printenv FOO
    env: {BAR: yyy, FOO: xxx$BAR}
```

this one gives string "qwe":

```yaml
task:
  - name: prints qwe
    script: printenv PASSWORD
    env: {PASSWORD: qwe$rty}
```

commands are also supported:

```yaml
task:
  - name: prints xxx
    script: printenv FOO
    env: {FOO: $(echo xxx)}
```

Golang's %q encoding may produce unexpected behavior. This task escapes new line character:

```yaml
task:
  - name: prints a\nb (new line is escaped)
    script: printenv FOO
    env: {FOO: "a\nb"}
```

this one escapes part of the emoji:

```yaml
task:
  - name: prints 👨\u200d🦰
    script: printenv FOO
    env: {FOO: 👨‍🦰}
```
