### ISSUE TITLE
Secrets partially exposed in playbook logs

### ISSUE THREAD

**Issue by vgr42** [umputun/spot#282]
Hi,

While exploring the secret handling feature, I noticed that secrets can sometimes be partially or fully shown in the simplified playbook execution log under certain conditions:

Playbook:

```yaml
local_shell: /bin/bash

tasks:
  - name: Test task
    options:
      local: true
      secrets:
        - secret
        - secret_special
    commands:
      - name: echo command
        script: echo "${secret} ${secret_special}"

```
1. 
`secret: password123`
`secret_special: password123#`

```shell
$ spot --secrets.provider=spot --secrets.key=test
spot v1.16.4-0f8691e-2025-02-05T18:38:44Z
[localhost] run task "Test task", commands: 1 (local)
[localhost] completed command "echo command" {script: /bin/bash -c 'secret="****"; secret_special="****#"; echo "${secret} ${secret_special}"'} (10ms)
[localhost] completed task "Test task", commands: 1 (11ms)
```
2.
`secret: token321`
`secret_special: password123#` (same as the previous one)

```shell
...
[localhost] completed command "echo command" {script: /bin/bash -c 'secret="****"; secret_special="password123#"; echo "${secret} ${secret_special}"'} (11ms)
...
```
3.
`secret: token321.`
`secret_special: password123#`

```shell
...
[localhost] completed command "echo command" {script: /bin/bash -c 'secret="token321."; secret_special="password123#"; echo "${secret} ${secret_special}"'} (8ms)
...
```
