### ISSUE TITLE
bug in exporting environment variables

### ISSUE THREAD

**Issue by aslushnikov** [umputun/spot#285]
Hi,

My spot version is `v1.17.0-364d6d5-2025-05-14T23:11:56Z`. I'm on Apple silicon MacOS. 

I have the following playbook:

```yml
ssh_key: /Users/aslushnikov/.ssh/id_ed25519

targets:
  example.com:
    hosts:
      - { host: "example.com", user: "root" }

# list of tasks, i.e. commands to execute
tasks:
  - name: reproduce issue
    targets: ["example.com"]
    commands:
      - name: export variable
        script: |
          export BCRYPT_PASSWORD='$2a$14$G.j2F3fm9wluTougUU52sOzePOvvpujjRrCoVp5qWVZ6qRJh58ISC' # foobarbaz
          echo "---- EXPORTED: ${BCRYPT_PASSWORD}"
        options: { local: true }

      - name: read variable
        script: |
          echo "---- PROPAGATED: ${BCRYPT_PASSWORD}"
        options: { local: true }
```

I expect the `BCRYPT_PASSWORD`to propagate as-is; however, it looks like `$2` and `$1` are being expanded.
Is this a bug, or do I use it wrong?

Thanks,
Andrey

P.S. Thank you for this awesome software.

**Comment by aslushnikov** [comment]
Ah, this actually looks the dupe of #256. 
Is there a way to disable this behavior?

**Comment by umputun** [comment]
Hi @ksanderer,

I've investigated and fixed this issue in PR #286. The problem was that shell positional parameters like `$2` in your bcrypt hash were being expanded when they shouldn't be.

The fix now properly handles environment variables containing:
- `$0`-`$9` patterns (positional parameters) - these are now wrapped in single quotes to prevent expansion
- `\$` escaped dollar signs - these are now correctly passed as literal `$` characters

For example:
- `BCRYPT_PASS=$2a$14$...` will now work correctly without the `$2` being expanded
- `VAR=test\$value` will be passed as `test$value`
- Normal variables like `PATH=$HOME/bin` still work as expected with expansion

Could you please test with the latest master version and let me know if it resolves your issue? The bcrypt password should now be passed correctly without corruption.

Thanks for reporting this!

**Comment by aslushnikov** [comment]
Just in case someone else stumbles upon this, this could be worked-around by encoding in base64:

```yml
ssh_key: /Users/aslushnikov/.ssh/id_ed25519

targets:
  example.com:
    hosts:
      - { host: "example.com", user: "root" }

# list of tasks, i.e. commands to execute
tasks:
  - name: reproduce issue
    targets: ["example.com"]
    commands:
      - name: export variable
        script: |
          BCRYPT_PASSWORD='$2a$14$G.j2F3fm9wluTougUU52sOzePOvvpujjRrCoVp5qWVZ6qRJh58ISC'
          export BCRYPT_PASSWORD_B64=$(echo "${BCRYPT_PASSWORD}" | base64)
          echo "---- EXPORTED: ${BCRYPT_PASSWORD}"
        options: { local: true }

      - name: read variable
        script: |
          BCRYPT_PASSWORD=$(echo "${BCRYPT_PASSWORD_B64}" | base64 -d)
          echo "---- PROPAGATED: ${BCRYPT_PASSWORD}"
        options: { local: true }
```
