### ISSUE TITLE
Alternative lightweight  playbook format

### ISSUE THREAD

**Issue by umputun** [umputun/spot#54]
I have created several playbooks today, and most of them are trivial. They have a single target (usually group and names) and a a single task

The idea is to support some simplified format to allow something not as rich as a complete playbook but more flexible compared to ad-hoc commands.

**Comment by umputun** [comment]
note: this is not a replacement for the current format, but rather additional one to support

**Comment by umputun** [comment]
Probably this one is too simple to be practical. I think we still need a top-level task with multiple commands, i.e.

```yml
task:
   - name: copy something
     copy: ....
   - name: sync something
     sync: ....
  - run something
     script: ....
````
