### ISSUE TITLE
Ability to add a check before the script execution

### ISSUE THREAD

**Issue by umputun** [umputun/spot#89]
This is the typical issue I'd like to address: let's say we have a command like this 

```yml
- name: add /data mount 
  script: echo "/dev/sdb1       /mnt/data   ext4    defaults        0       0"  >>  /etc/fstab
  options: {sudo: true}
```

This script is not idempotent, and will gladly add the line as many times as the command executed

Currently, it can be handled as a part of the script, i.e, with something like this:

```
  script: |
    if ! grep -qs "/mnt/data" /etc/fstab; then
       echo "/dev/sdb1       /mnt/data   ext4    defaults        0       0"  | sudo tee -a /etc/fstab
    fi
```

I'm not sure if this is the best way. It is simple for sure, but having to write ifs to multiple commands can make the command hard to read. Maybe we want to split it by introducing a new "condition" field? I mean something like this:

```yml
- name: add /data mount 
   script: echo "/dev/sdb1       /mnt/data   ext4    defaults        0       0"  >>  /etc/fstab
   options: {sudo: true}
   cond: grep -vqs "/mnt/data" /etc/fstab
```

This way condition and the actual script are separated, and the command will skip the script's execution if the condition returns non-zero

I'm not sure about this - it adds a new element on one hand but potentially simplifies the script on another. Let me know what you think about this idea
